<?php echo $this->doctype(); ?>
<html class="no-js" ng-app="marketplaceApp" ng-controller="MainCtrl">
<head>
  <meta charset="utf-8">
  <base href="<?php echo $this->url('home'); ?>">
  <title>Marketplace</title>
  <meta name="description" content="">
  <?php echo $this->headMeta()
      ->appendName('viewport', 'width=device-width, initial-scale=1.0')
      ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
  ?>
  <!-- build:css(.) styles/vendor.css -->
  <!-- bower:css -->
  <!-- endbower -->
  <!-- endbuild -->
  <!-- build:css(.tmp) styles/main.css -->
  <link rel="stylesheet" href="styles/app.css">
  <link rel="stylesheet" href="styles/direct-icons.css">
  <!-- endbuild -->
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
  <link rel="icon" type="image/png" href="/favicon-192x192.png" sizes="192x192">
  <link rel="icon" type="image/png" href="/favicon-160x160.png" sizes="160x160">
  <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
  <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
  <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="msapplication-TileImage" content="/mstile-144x144.png">
</head>
<body>


<?php if ($this->success === false) : ?>
  <div class="alert alert-danger">
    <button class="close" data-close="alert"></button>
    <span><?php echo $this->escapeHtml($this->message); ?></span>
  </div>
<?php endif; ?>


<!--Login-->
<div ng-show="!isNewPass" ng-controller="LoginCtrl">
  <div id="login" ng-hide="isForgotten">
    <div class="header"><img src="/images/logo_market_place.png"></div>
    <div class="login">
      <form action method="POST" name="form-login" id="form-login">
        <input type="text" name="username" required="required" placeholder="e-mail" id="username" value="">
        <input type="password" name="password" required="required" placeholder="senha" id="password" value="">
        <button type="submit" class="btn btn-primary" id="mainLoginButton">Entrar</button>
      </form>
      <button type="button" ng-click="resetPass()" class="link-button">Esqueci a senha</button>
    </div>
  </div>


  <!--Esqueci minha senha-->
  <div id="reset-pass" ng-show="isForgotten && !isSendEmail">
    <div class="header"><img src="/images/logo_market_place.png"></div>
    <div class="login">
      <form class="reset-pass">
        <h3>Esqueceu sua senha?</h3>
        <div>
          <p>Digite o endereço de e-mail usado para criar sua conta.</p>
          <p>Vamos localizar suas informações e lhe enviar um e-mail com um link para redefinir sua senha.</p>
        </div>
        <fieldset>
          <input type="text" placeholder="e-mail">
          <button type="button" class="btn btn-primary" ng-click="sendEmail()">Enviar</button>
          <button type="button" class="btn btn-info" ng-click="resetPass()">cancelar</button>
        </fieldset>
      </form>
    </div>
  </div>


  <!--Email enviado-->
  <div id="sendEmail" ng-show="isForgotten && isSendEmail">
    <div class="header"><img src="/images/logo_market_place.png"></div>
    <div class="login">
      <form class="reset-pass">
        <h3>Esqueceu sua senha?</h3>
        <div>
          <p>Confira seu e-mail! Enviamos um link para que você possa redefinir sua senha.</p>
          <p>Este e-mail contém um link que o levará para uma página onde você pode criar uma nova senha.</p>
          <p>Se você não receber este e-mail dentro de alguns minutos, verifique sua pasta de spam, ou envie um outro pedido.</p>
        </div>
        <fieldset>
          <button type="button" class="btn btn-info" ng-click="isSendEmail = false">enviar o email novamente</button>
          <button type="button" class="btn btn-primary" ng-click="resetPass()">login</button>
        </fieldset>
      </form>
    </div>
  </div>
</div>

<!--Definir senha-->
<div ng-show="isNewPass" ng-controller="LoginCtrl">
  <div class="header"><img src="/images/logo_market_place.png"></div>
  <div class="login">
    <form class="reset-pass new-pass">
      <h3>Definir senha</h3>
      <strong>Por favor defina uma nova senha</strong>
      <div>
        <p>Para que sua senha seja válida ela deve ter no mínimo:</p>
        <p>8 caracteres - uma letra maíuscula - uma letra minúscula - um número.</p>
      </div>
      <table>
        <tr><td>Senha</td><td>Confirme a senha</td></tr>
        <tr><td><input type="password" placeholder="senha"></td><td><input type="password" placeholder="senha"></td></tr>
      </table>
      <fieldset>
        <button type="button" class="btn btn-info" ng-click="isNewPass = false">cancelar</button>
        <button type="button" class="btn btn-primary" ng-click="isNewPass = false">salvar</button>
      </fieldset>
    </form>
  </div>
</div>

<footer class="footer">
  <div class="container">
    <span class="ficon ficon-heart"></span> Predicta &amp; Direct &copy; 2014
  </div>
</footer>


    <!-- build:js(.) scripts/oldieshim.js -->
    <!--[if lt IE 9]>
    <script src="bower_components/es5-shim/es5-shim.js"></script>
    <script src="bower_components/json3/lib/json3.js"></script>
    <![endif]-->
    <!-- endbuild -->

    <!-- build:js(.) scripts/vendor.js -->
    <!-- bower:js -->
    <script src="bower_components/jquery/dist/jquery.js"></script>
    <script src="bower_components/angular/angular.js"></script>
    <script src="bower_components/angular-animate/angular-animate.js"></script>
    <script src="bower_components/angular-aria/angular-aria.js"></script>
    <script src="bower_components/angular-cookies/angular-cookies.js"></script>
    <script src="bower_components/angular-messages/angular-messages.js"></script>
    <script src="bower_components/angular-resource/angular-resource.js"></script>
    <script src="bower_components/angular-route/angular-route.js"></script>
    <script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
    <script src="bower_components/angular-touch/angular-touch.js"></script>
    <script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
    <script src="bower_components/angular-route-styles/route-styles.js"></script>
    <script src="bower_components/angular-local-storage/dist/angular-local-storage.js"></script>
    <!-- endbower -->
    <!-- endbuild -->

    <!-- build:js({.tmp,app}) scripts/scripts.js -->
    <script src="bower_components/angular-i18n/angular-locale_pt-br.js"></script>
    <script src="scripts/components/angular-multiselect.js"></script>
    <script src="scripts/marketplace-templates.js"></script>
    <script src="scripts/ui-templates.js"></script>
    <script src="scripts/ui-multiselect.js"></script>
    <script src="scripts/app.js"></script>
    <script src="scripts/shared/mainServices.js"></script>
    <script src="scripts/shared/mainCtrl.js"></script>
    <script src="scripts/shared/nav/navCtrl.js"></script>
    <script src="scripts/shared/login/loginCtrl.js"></script>
    <script src="scripts/shared/utils/modalConfirmCtrl.js"></script>
    <script src="scripts/components/results/resultsFilters.js"></script>
    <script src="scripts/components/results/resultsCtrl.js"></script>
    <script src="scripts/components/results/resultsServices.js"></script>
    <script src="scripts/components/filter/filterCtrl.js"></script>
    <script src="scripts/components/search/searchCtrl.js"></script>
    <script src="scripts/components/purchases/purchasesCtrl.js"></script>
    <script src="scripts/components/bids/bidsCtrl.js"></script>
    <script src="scripts/components/campaigns/campaignsCtrl.js"></script>
    <!-- endbuild -->

</body>
</html>
