// Generated by CoffeeScript 1.8.0
exports.config = {
  allScriptsTimeout: 11000,
  seleniumAddress: 'http://localhost:4444/wd/hub',
  capabilities: {
    browserName: 'chrome'
  },
  onPrepare: function() {
    browser.driver.manage().window().setSize(1200, 800);
    global.By = global.by;
  },
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    includeStackTrace: true,
    isVerbose: true
  },
  specs: ['spec.coffee'],
  params: {
    login: {
      user: 'leandro.lages@predicta.net',
      pass: 'fa0gc5'
    }
  }
};
